# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "$GITHUB_REF_NAME"
          case "$GITHUB_REF_NAME" in
            "origin/develop")
              echo "dev"
              ;;
            "origin/main")
              echo "main"
              ;;
            *)
              echo "[ERROR] - Branch no reconocida."
              exit 0
              ;;
          esac
